// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod mik {
        pub mod core {
            /// Minimal handler interface - all types inline.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod handler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// HTTP methods.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Method {
                    Get,
                    Post,
                    Put,
                    Patch,
                    Delete,
                    Head,
                    Options,
                }
                impl ::core::fmt::Debug for Method {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Method::Get => f.debug_tuple("Method::Get").finish(),
                            Method::Post => f.debug_tuple("Method::Post").finish(),
                            Method::Put => f.debug_tuple("Method::Put").finish(),
                            Method::Patch => f.debug_tuple("Method::Patch").finish(),
                            Method::Delete => f.debug_tuple("Method::Delete").finish(),
                            Method::Head => f.debug_tuple("Method::Head").finish(),
                            Method::Options => f.debug_tuple("Method::Options").finish(),
                        }
                    }
                }
                impl Method {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Method {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Method::Get,
                            1 => Method::Post,
                            2 => Method::Put,
                            3 => Method::Patch,
                            4 => Method::Delete,
                            5 => Method::Head,
                            6 => Method::Options,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// HTTP request data from the bridge.
                #[derive(Clone)]
                pub struct RequestData {
                    pub method: Method,
                    pub path: _rt::String,
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for RequestData {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RequestData")
                            .field("method", &self.method)
                            .field("path", &self.path)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                /// HTTP response.
                #[derive(Clone)]
                pub struct Response {
                    pub status: u16,
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    pub body: Option<_rt::Vec<u8>>,
                }
                impl ::core::fmt::Debug for Response {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Response")
                            .field("status", &self.status)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i32,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base7 = arg3;
                    let len7 = arg4;
                    let mut result7 = _rt::Vec::with_capacity(len7);
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e7 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            (_rt::string_lift(bytes3), _rt::string_lift(bytes6))
                        };
                        result7.push(e7);
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result9 = T::handle(RequestData {
                        method: Method::_lift(arg0 as u8),
                        path: _rt::string_lift(bytes0),
                        headers: result7,
                        body: match arg5 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len8 = arg7;
                                    _rt::Vec::from_raw_parts(arg6.cast(), len8, len8)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Response {
                        status: status11,
                        headers: headers11,
                        body: body11,
                    } = result9;
                    *ptr10.add(0).cast::<u16>() = (_rt::as_i32(status11)) as u16;
                    let vec15 = headers11;
                    let len15 = vec15.len();
                    let layout15 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec15.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result15 = if layout15.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout15).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout15);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec15.into_iter().enumerate() {
                        let base = result15
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t12_0, t12_1) = e;
                            let vec13 = (t12_0.into_bytes()).into_boxed_slice();
                            let ptr13 = vec13.as_ptr().cast::<u8>();
                            let len13 = vec13.len();
                            ::core::mem::forget(vec13);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len13;
                            *base.add(0).cast::<*mut u8>() = ptr13.cast_mut();
                            let vec14 = (t12_1.into_bytes()).into_boxed_slice();
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            ::core::mem::forget(vec14);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len14;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr14.cast_mut();
                        }
                    }
                    *ptr10
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len15;
                    *ptr10.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result15;
                    match body11 {
                        Some(e) => {
                            *ptr10
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec16 = (e).into_boxed_slice();
                            let ptr16 = vec16.as_ptr().cast::<u8>();
                            let len16 = vec16.len();
                            ::core::mem::forget(vec16);
                            *ptr10
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len16;
                            *ptr10
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr16.cast_mut();
                        }
                        None => {
                            *ptr10
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr10
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l7 = i32::from(
                        *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l7 {
                        0 => {}
                        _ => {
                            let l8 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l8;
                            let len10 = l9;
                            _rt::cabi_dealloc(base10, len10 * 1, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Process an HTTP request and return a response.
                    fn handle(req: RequestData) -> Response;
                }
                #[doc(hidden)]
                macro_rules! __export_mik_core_handler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "mik:core/handler@0.1.0#handle")] unsafe extern "C" fn
                        export_handle(arg0 : i32, arg1 : * mut u8, arg2 : usize, arg3 : *
                        mut u8, arg4 : usize, arg5 : i32, arg6 : * mut u8, arg7 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_handle_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5,
                        arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_mik:core/handler@0.1.0#handle")] unsafe extern "C" fn
                        _post_return_handle(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_handle::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_mik_core_handler_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 6
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_hello_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::mik::core::handler::__export_mik_core_handler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::mik::core::handler);
    };
}
#[doc(inline)]
pub(crate) use __export_hello_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:mik:hello-world@0.1.0:hello-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 383] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfd\x01\x01A\x02\x01\
A\x02\x01B\x0c\x01m\x07\x03get\x04post\x03put\x05patch\x06delete\x04head\x07opti\
ons\x04\0\x06method\x03\0\0\x01o\x02ss\x01p\x02\x01p}\x01k\x04\x01r\x04\x06metho\
d\x01\x04paths\x07headers\x03\x04body\x05\x04\0\x0crequest-data\x03\0\x06\x01r\x03\
\x06status{\x07headers\x03\x04body\x05\x04\0\x08response\x03\0\x08\x01@\x01\x03r\
eq\x07\0\x09\x04\0\x06handle\x01\x0a\x04\0\x16mik:core/handler@0.1.0\x05\0\x04\0\
!mik:hello-world/hello-world@0.1.0\x04\0\x0b\x11\x01\0\x0bhello-world\x03\0\0\0G\
\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen\
-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
